### ISSUE TITLE
is it possible to support HDFS as disk storage

### ISSUE THREAD

**Issue by at15** [msvens/mellowtech-core#2]
Hi, I am curious about if it is possible to implement the BPlusTree using HDFS as backend.  There is some paper and project using old version of mellowtech core to build BPTree index for HDFS (see Appendix), and I think it might be a useful feature for data warehouse system.

But there are some problem for using mellowtech core on HDFS

- HDFS can only append data to file, insert is not allowed.
- HDFS does not support random read well.
- mellowtech-core now requires java8, while most HDFS runs on java7

##### KNN 

this project https://github.com/sashashan/mapreduce/tree/master/mrknnj-release/hzknnj use the old version of mellowtech-core to achieve KNN index on HDFS, the code is quite a mess I don't know how it
uses the BPTree....

> To compile these file, a B+ tree library is required. We include the library
package name as btree.tar.bz2 in this tar file. The library can be also be found 
in the following link: http://www.sics.se/humle/socialcomputing/download/

##### A Generic tree like index in the cloud

this paper[A Generic tree like index in the cloud](https://books.google.com/books?id=L0u7BQAAQBAJ&pg=PA335&lpg=PA335&dq=hdfs+b%2B+index&source=bl&ots=AqRVkSaj-y&sig=xwbJenZTeV9oZxbqNQuLWM7s4P0&hl=en&sa=X&ved=0ahUKEwj1hoHjn9PJAhUBVD4KHdM6ArgQ6AEIMTAD#v=onepage&q=hdfs%20b%2B%20index&f=false) might be using mellowtech core as well

it has a picture for its index structure, which is not available online, so I attached it below, is very similar to mellowtech-core's 
<img width="891" alt="c-index" src="https://cloud.githubusercontent.com/assets/5621298/11916878/04364318-a727-11e5-8800-3fdb21b9eee0.png">

the basic idea for that paper, which is also my homework XD , is to 

- partition the data and build BPTree index for each partition
- use bulk loading to create the index, and once it is built, it will never change unless rebuild
- store the partition info in a meta table, a plain small text file in HDFS
- for new data, create a new partition and sub-index, merge the sub-indexes if there are too many
- for point query, query one partition directly 
- for range query, get all the partition in range, if one partition, same as point, otherwise, start  map reduce to query in parallel and merge result.

a example for meta table, store partition and range
`````
partition    start    end   count
part-000     1       1000   200
part-001     1001    2000  100
`````
so when I query `SELECT * FROM students WHERE id = 90`, it will query the first partition, and for `SELECT * FROM students WHERE id > 900 AND id < 1100`, it will launch a map reduce to query the two partition in parallel and merge the result.

I guess they rewrote the IO part for mellowtech core to store index on HDFS

**Comment by msvens** [comment]
Yes, I have thought about HDFS but scrapped the idea because of the reasons you mention in the beginning. If one would do it though the solution in the paper sounds like a plausible way to do it. Still if one would want to do a distributed version I would first look at other key-value stores out there (hbase or cassandra) and make sure they don't suite the the needs before implementing your own solution. If you however want to it I don't necessarily think hdfs would be the way to go - unless you really need the map-reduce parts. So at the moment I have no plans on doing something like that.

Having that said, if you are interested in taking on the challenge I would be very glad to help/assist

**Comment by at15** [comment]
@msvens Thanks for reply, like you said I would use  hbase or cassandra if I want to have better query speed for large dataset, most time I use elasticsearch for search engine. I have this idea mainly because it's  a final project for my course, which is to write B+ index to speed up Hive query speed, because Hive only have bitmap index and compact index.  I think I might have a try on this next month after all the tests... 

As for my project, I use a really dumb method, all the sub-index are  built locally in reducer and then uploaded to HDFS, when query multiple sub-indexes, launch a map reduce to query multiple sub-indexes in parallel, reducer download a local copy if not exists and query on that local copy directly, then merge all the result and return to client. 

I guess I will just close this issue now, and may reopen it when I have time or better idea, thanks~
