### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by at15** [msvens/mellowtech-core#3]
Hi, I find mellowtech-core does not have a `LICENSE` file in repo, and it's not mentioned in README as well, though it does have `apache2.0` in `pom.xml`, maybe it's better to put it in a more conspicuous place?

**Comment by msvens** [comment]
Good point. I will put this in the backlog and also create a proper license statement in each source file

**Comment by msvens** [comment]
Added license file and changed copyright statement in source files to match the license. This issue will be closed
